# Generated by Django 4.0.3 on 2022-03-26 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccn', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express')], max_length=30)),
                ('exp_date', models.DateField(null=True)),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default=1, max_length=30)),
                ('team1', models.CharField(max_length=30)),
                ('team2', models.CharField(max_length=30)),
                ('spread', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_selection', models.CharField(choices=[('Home', 'Home team'), ('Away', 'Away team')], default='Home', max_length=30)),
                ('bet_amount', models.IntegerField()),
                ('bet_time', models.DateTimeField(default=datetime.datetime(2022, 3, 26, 18, 13, 28, 286784), editable=False)),
                ('bet_note', models.CharField(max_length=200)),
                ('gameID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
    ]
