# Generated by Django 4.0.3 on 2022-03-26 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp_date',
            field=models.DateField(default=datetime.date(2022, 3, 26)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 18, 16, 11, 776649), editable=False),
        ),
    ]
