# Generated by Django 4.0.3 on 2022-03-26 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_exp_date_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 18, 31, 34, 485826), editable=False),
        ),
    ]
