# Generated by Django 4.0.3 on 2022-04-30 01:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bet_bet_time_alter_bet_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccn', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express')], max_length=30)),
                ('exp_date', models.DateField(default=datetime.date(2022, 4, 29))),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ccn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='account',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 21, 47, 4, 488904), editable=False),
        ),
        migrations.AddField(
            model_name='account',
            name='paymentID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.paymentmethod'),
            preserve_default=False,
        ),
    ]
