# Generated by Django 4.0.3 on 2022-04-30 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_paymentmethod_remove_account_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='paymentID',
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 21, 54, 57, 414172), editable=False),
        ),
    ]
