# Generated by Django 4.0.3 on 2022-04-30 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_account_paymentid_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 21, 55, 36, 389423), editable=False),
        ),
    ]
