# Generated by Django 4.0.3 on 2022-04-30 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paymentID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.paymentmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 22, 4, 43, 559972), editable=False),
        ),
    ]
