# Generated by Django 4.0.4 on 2022-04-30 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_paymentmethod_accountid_paymentmethod_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 14, 10, 16, 440479), editable=False),
        ),
    ]
