# Generated by Django 4.0.3 on 2022-05-01 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('Loss/In Progress', 'Loss/Incomplete'), ('Win', 'Win')], default='Loss/In Progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 13, 37, 55, 523371)),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='exp_date',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
