# Generated by Django 4.0.4 on 2022-04-30 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 16, 5, 1, 483953), editable=False),
        ),
    ]
