# Generated by Django 4.0.3 on 2022-05-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_bet_bet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 14, 10, 10, 719383)),
        ),
    ]
